[gcp_service_account]
type = "service_account"
project_id = "docfinaceiro"
private_key_id = "4eac30602b61b9ee01aa5652d2a0a15e7676cfb0"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC+jmmCTsG2+Jmx
1EQij47Zyw4c4jBTc3xAty+Tv8PvLjQV4otSXCQltaLj+FhZl1KGWFDOhNfTB3dy
fZBfdLnQVwVfUZgp+WfIDEK7rOh5zTShbJdyd6Cd/ddNysmCs2tXUi5UdUN74Mn7
MSzogyxg9RPcKOxR0xg/7yYSTKwwixmKCin+TSKD6fH6r+D6DdNdpFNMpIglx/DO
VhIvfWOp0k+57hq8jSBR2QoZxM3Dv5LytlEojnLKHr6pSiuNjEu2kgfD4kIOkyj+
gBN2TnZBzyADP5J+xNY9oKGAg9puW3tI1HI7Tmzrp2S7tOmACTS8X/rQf2Zg8nQK
bjPbqV7vAgMBAAECggEAXgledQFTpG1TP4geZaXNm5oSqVtP+Oa9UxxzfKi+UurM
pl4pXef9qKRVscWtJ+0+uvCbVAcHkOsW3aesVwb96ZwAGTVlb5VWS0kNp5shEHad
eeniZQk2+LC7jva7ceYD21BBb8l8l4Xrdywh2s5c2K4o8lU5pfmT9n0YnyA6OyuX
HAtiihSSQDxljHX/5C4ENqDavtGUvI3bhPnQSoI4rOApeoHySsbkGzb6Do+V4wyv
XLOj25cxhMCSwqdVXO5OssIwQR1XLIQvPLgsVLOvpUKr+EjL9cyL6AxyQPkRzXsH
PTUAuxJi3zzAI63nf2+9VfVU/ar5A4/6l1Og9g8RvQKBgQDwBvxTrPNfweais2FH
Jo5UEkE5h8usGt7wk+hZmaCAG64EWC1aaUmu4P6dL2BYsYF9r3vkeI1ka+2gea2n
BsMsU07hAolzERP/cl3RRkkYjCMo5o7IarpK+hS4ABrbESJjUy/02s6pe5JTligt
aM/vEnMfKCy1PxPZE8z0245hMwKBgQDLPKhIxcmCchvFNo2uTmEgT5wIubYaHnsF
oMEBj188glhP/8yD7I7b9pPVJ6VFIj5BAjfN1j9h0l8MMzphf4qk8yncdjEzcHuV
HLxBNQDvP7hPykGVCyLb3vD8rnrbUgYdqSsxVfp5bTpPfWtuxerh7DBQhrvYI8X2
jC4cy8KDVQKBgFe7Fes3odT0OGprijjJXOhZq8FtYwJK6AWi6iAlyMZKV7Z6zEjp
hucGkcm+EUcZyiy4QV5mubdkw3wOPWx5SkkfQgt4M+j86wRJNwVQ3VK9lfRTIQkc
CW9yLLR8RVSg1KLdOwASIctMwVUP4yuFzcqiQbW3p2+v2H9Vf2pX/ZiFAoGBAKxL
TQL8ojtzDzXebLgzfEWPF+GRxt5XrsVzpYv0BrHeco3HdpL0jZvOaz9OL97vC8XC
4poeoncEiE1odHrJTDlQZ9GdZVKNbkdYKARDsfohk9gYyAZZfYDWfIhKRp79529n
xdU6ZXBheAiBc/1hziEfQUpTHpY6pY3BAyqoVstNAoGBALMrRnpHrMjpCR+6Qqpr
v+QiNUEGRq/HCHvBVX34g+Et8Dt0SyDkMkk7b/mFxInq94ajOW9Ek7pkUZ8FIWZN
Xr9mSWQRw9NfvSxrBPankSw5CzxFiuXgsII6HIur75QSvjhJZUN5DAZ91JoFDFah
jhBQA/VB6IDr8Z5ojpxjUFE/
-----END PRIVATE KEY-----
"""
client_email = "relatorio-gestor@docfinaceiro.iam.gserviceaccount.com"
client_id = "104546901566411050807"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/relatorio-gestor@docfinaceiro.iam.gserviceaccount.com"
universe_domain = "googleapis.com"